### ISSUE TITLE
multicastLock and JmDNS

### ISSUE THREAD

**Issue by nezen** [twitwi/AndroidDnssdDemo#1]
JmDNS supports service discovery and service registration.My question is, which one requires multicastLock? An explanation would be appreciated.

**Comment by twitwi** [comment]
My understanding of the lock is that it is necessary to actually receive multicast packets [1].
Thus, I'd say that it is at least mandatory when you want to achieve discovery.

I don't know the details of the mDNS protocol, but I think that it is kind of request-response [2](all over multicast) so even service registration would need the lock.

[1] https://developer.android.com/reference/android/net/wifi/WifiManager.MulticastLock.html
[2] https://en.wikipedia.org/wiki/Multicast_DNS#Protocol_overview

**Comment by nezen** [comment]
Thanks for your replay. I've been working on an android app based on JmDNS. My app discovers some devices from the local Wi-Fi network. So far it does work even without the multicastlock on my test phones.But I'm not sure what will happen on the others phones. It seems I have to dig deep before I can figure it out.

**Comment by twitwi** [comment]
Ok, thanks. If you figure out more about this, please post it here as it as people might en up on this issue later.
